### ISSUE TITLE
This is not issue :)

### ISSUE THREAD

**Issue by eemirtekin** [jibon57/bbb-recorder#11]
Hi Jibon,
This is great project.
Thanks to this project, we have implemented our BBB dashboard downloading MP4 future.

Thanks again.

![WhatsApp Image 2020-04-22 at 11 13 06 PM](https://user-images.githubusercontent.com/1687805/80029124-fa9e9080-84ee-11ea-9739-c5ac76404e82.jpeg)
![WhatsApp Image 2020-04-22 at 11 13 07 PM](https://user-images.githubusercontent.com/1687805/80029147-038f6200-84ef-11ea-94ed-f80492d40893.jpeg)
![WhatsApp Image 2020-04-22 at 11 13 07 PM (1)](https://user-images.githubusercontent.com/1687805/80029160-08541600-84ef-11ea-9b3a-d50ea7dd0622.jpeg)

**Comment by jibon57** [comment]
Excellent. You are welcome to pull back to repo (of course if you want). But really happy to see 👍

**Comment by eemirtekin** [comment]
Hi Again,
We used simple API developed with flask to run your script on dashboard.
Really working successfully.
This dashboard is private.
Thanks again.

**Comment by jibon57** [comment]
Nice, anyone can use websocket easily to perform node process.
