### ISSUE TITLE
using external server

### ISSUE THREAD

**Issue by MudrekaBohra** [jibon57/bbb-recorder#12]
hello everyone,
first off a very big thank you for developing a much needed solution 
please sir can you explain how i can set up a secondary server just to process and store the recording i am using php how can i make this process easy or automated and then retrieve the recording or multiple recordings with meeting id 
thanks in advanced

**Comment by jibon57** [comment]
That's on you. You can setup your own development using PHP. You can follow this: https://github.com/jibon57/bbb-recorder/issues/2#issuecomment-607866970
