### ISSUE TITLE
using bbb-recorder in another server - PHP scripts

### ISSUE THREAD

**Issue by damiansanguine** [jibon57/bbb-recorder#13]
Hi Jibon,

thanks for your solution. This is what we were looking for!

we want to setup a separate box to process videos using the BBB hook. 
we will:
1. setup the hook to our bbb-recorder box
2. get the duration of the video using getRecordings API.
3. convert to mp4
4. we will use meetingid as name.
5. we will leave file in S3.

do you have the PHP scripts or in any other language that you might setup so we can based on that?

then we can share our solution.

thanks!

**Comment by jibon57** [comment]
No, sorry. You'll have to find your own solution.
