### ISSUE TITLE
Error when running script for recording export

### ISSUE THREAD

**Issue by astroviki** [jibon57/bbb-recorder#16]
After succesfull installation a tried to export recording to mp4 file using command

node export.js "https://bbbvoip.upvsp.cz/playback/presentation/2.0/playback.html?meetingId=d075cf94b0bd47cde1cb0c75d54edd97113339ad-1588181572758" meeting.webm 0 true

I checked and playback record in Moodle, everything works fine. When I tried to export meeting to mp4 but it failed with error:

PAGE LOG: ==Getting URL params
PAGE LOG: ==DOM content loaded
PAGE LOG: ==Resizing components
PAGE LOG: ==Resizing components
PAGE LOG: ==Resizing components
PAGE LOG: ==Resizing components
PAGE LOG: ==Resizing components
PAGE LOG: ==Resizing components
PAGE LOG: ==Resizing components
PAGE LOG: ==Resizing components
PAGE LOG: ==Processing metadata.xml
PAGE LOG: Failed to load resource: the server responded with a status of 404 (Not Found)
PAGE LOG: Failed to load resource: the server responded with a status of 404 (Not Found)
PAGE LOG: Failed to load resource: the server responded with a status of 404 (Not Found)
PAGE LOG: ==Found video /presentation/d075cf94b0bd47cde1cb0c75d54edd97113339ad-1588181572758/video/webcams.webm
PAGE LOG: ==Loading playback
PAGE LOG: ==Hide playback content
PAGE LOG: ==Loaded logo from logo.png
PAGE LOG: ==Loading video
PAGE LOG: ==Loading acorn media player
PAGE LOG: ==Processing shapes.svg
PAGE LOG: ==Processing panzooms.xml
PAGE LOG: ==Processing cursor.xml
PAGE LOG: ==Processing deskshare.xml
PAGE LOG: ==Processing captions.json
PAGE LOG: ==Resizing components
PAGE LOG: ==Processing presentation_text.json
PAGE LOG: ==All medias can be played
PAGE LOG: ==Linking chat to media
PAGE LOG: ==Running popcorn
PAGE LOG: 'webkitRequestAnimationFrame' is vendor-specific. Please use the standard 'requestAnimationFrame' instead.
PAGE LOG: ==Generating thumbnails
PAGE LOG: ==Setting title on thumbnails
PAGE LOG: ==Defining start time
PAGE LOG: ==Loading done
PAGE LOG: ==Show playback content
PAGE LOG: ==Resizing components
PAGE LOG: REC_START
/var/www/bigbluebutton-default/record/meeting.mp4
/root/Downloads/meeting.webm
converting using: ffmpeg -y -i '/root/Downloads/meeting.webm' -c:v libx264 -preset veryfast -movflags faststart -profile:v high -level 4.2 -max_muxing_queue_size 9999 -vf mpdecimate -vsync vfr '/var/www/bigbluebutton-default/record/meeting.mp4'
err:
Error: Command failed: ffmpeg -y -i '/root/Downloads/meeting.webm' -c:v libx264 -preset veryfast -movflags faststart -profile:v high -level 4.2 -max_muxing_queue_size 9999 -vf mpdecimate -vsync vfr '/var/www/bigbluebutton-default/record/meeting.mp4'
ffmpeg version 4.2.2-1bbb1~ubuntu16.04 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 20160609
  configuration: --prefix=/usr --extra-version='1bbb1~ubuntu16.04' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-librsvg --enable-librubberband --enable-libspeex --enable-libvorbis --enable-libvpx --enable-libxml2 --enable-sdl2 --disable-decoders --enable-decoder='aac,ass,bmp,ffv1,ffvhuff,flac,flashsv,flashsv2,flv,gif,h264,huffyuv,librsvg,libspeex,mjpeg,mp3float,mpeg2video,opus,pcm_f32le,pcm_s16le,pcm_s16le_planar,png,rawvideo,srt,ssa,subrip,vorbis,vp6,vp6a,vp6f,vp8,vp9,webp,webvtt' --disable-encoders --enable-encoder='aac,ass,bmp,ffv1,ffvhuff,flac,flashsv,flashsv2,flv,gif,h264_vaapi,huffyuv,libmp3lame,libopus,libspeex,libvorbis,libvpx_vp8,libvpx_vp9,libx264,libx264rgb,mjpeg,mjpeg_vaapi,mpeg2_vaapi,mpeg2video,pcm_f32le,pcm_s16le,pcm_s16le_planar,png,rawvideo,srt,ssa,subrip,vp8_vaapi,vp9_vaapi,webvtt' --disable-hwaccels --enable-hwaccel='h264_vaapi,h264_vdpau,mjpeg_vaapi,mpeg2_vaapi,mpeg2_vdpau,vp8_vaapi,vp9_vaapi' --disable-parsers --enable-parser='aac,bmp,flac,gif,h264,mjpeg,mpegaudio,mpegvideo,opus,png,vorbis,vp8,vp9' --disable-demuxers --enable-demuxer='aac,alsa,ass,avi,bmp_pipe,caf,concat,dash,ffmetadata,flac,flv,gif,gif_pipe,h264,hls,image2,image2pipe,ivf,jpeg_pipe,kmsgrab,lavfi,matroska,mjpeg,mov,mp3,mpegts,mpegtsraw,nut,ogg,pcm_f32le,pcm_s16le,png_pipe,pulse,rawvideo,rtp,rtsp,srt,swf,w64,wav,webvtt,yuv4mpegpipe' --disable-muxers --enable-muxer='adts,ass,avi,caf,dash,ffmetadata,flac,flv,framecrc,framehash,framemd5,gif,h264,hash,hls,image2,image2pipe,ipod,ivf,matroska,matroska_audio,md5,mjpeg,mkvtimestamp_v2,mov,mp3,mp4,mpeg2video,mpegts,nut,oga,ogg,ogv,opus,pcm_f32le,pcm_s16le,rawvideo,rtp,rtp_mpegts,rtsp,segment,singlejpeg,srt,stream_segment,swf,tee,uncodedframecrc,w64,wav,webm,webm_chunk,webm_dash_manifest,webvtt,yuv4mpegpipe' --disable-protocols --enable-protocol='async,cache,concat,data,file,hls,http,httpproxy,https,icecast,md5,pipe,rtmp,rtmps,rtmpt,rtmpts,rtp,subfile,tcp,tee,tls,udp,unix' --disable-bsfs --enable-bsf='aac_adtstoasc,chomp,filter_units,h264_metadata,h264_mp4toannexb,h264_redundant_pps,mjpeg2jpeg,mpeg2_metadata,noise,null,vp9_metadata,vp9_raw_reorder,vp9_superframe,vp9_superframe_split' --disable-indevs --enable-indev='alsa,lavfi,v4l2,fbdev,xcbgrab,kmsgrab' --disable-outdevs --enable-outdev='alsa,sdl2,xv,fbdev,v4l2' --disable-libdc1394 --enable-libdrm --disable-libiec61883 --disable-chromaprint --disable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
/root/Downloads/meeting.webm: Invalid data found when processing input

Can yoy help me where is the problem ?

**Comment by jibon57** [comment]
node export.js "https://bbbvoip.upvsp.cz/playback/presentation/2.0/playback.html?meetingId=d075cf94b0bd47cde1cb0c75d54edd97113339ad-1588181572758" meeting.webm **0** true

Why **0**?

It should have some value **greater than 0**

`node export.js "https://bbbvoip.upvsp.cz/playback/presentation/2.0/playback.html?meetingId=d075cf94b0bd47cde1cb0c75d54edd97113339ad-1588181572758" meeting.webm 20 true`
