### ISSUE TITLE
Trouble with some recordings

### ISSUE THREAD

**Issue by daigonstar** [jibon57/bbb-recorder#19]
HI there 

Not sure is this is an issue or not with a few longer recordings 50 mins +
We keep getting logs underneath the REC Start not sure is this is stopping recording from happening.
![image](https://user-images.githubusercontent.com/62888776/81071745-0ae64080-8edd-11ea-9fc5-63ef51e5d6fb.png)

**Comment by jibon57** [comment]
That's console log messages.
