### ISSUE TITLE
Use  metadata.xml or ffprobe to find duration

### ISSUE THREAD

**Issue by marshel** [jibon57/bbb-recorder#2]
Hi, instead of setting manually the duration you could set in your script to search for video duration on metadata.xml,  getting end time and subtract start time and then divide by 1000 for getting the seconds.

`<start_time>1585088145458</start_time>  <end_time>1585091756843</end_time>`

or use the terminal command below:

`ffprobe -i some_video -show_entries format=duration -v quiet -of csv="p=0"
`
if the meeting was recorded with a webcam.

Best regards.

**Comment by jibon57** [comment]
@marshel , thanks for the suggestion. I'll recommend to use different server for this solution. In my case I have hired a small VPS with 4 cores. I can easily run at least 4~5 process at a same time. For getting recordings information I'll recommend to call [getRecordings](http://docs.bigbluebutton.org/dev/api.html#getrecordings) API.

**Comment by jibon57** [comment]
If you are planning to export every meeting's recording then you can use [Recording ready callback URL](http://docs.bigbluebutton.org/dev/api.html#recording-ready-callback-url) feature. So, when the BBB will complete recording that time you'll get notification & can use `bbb-recorder` to start it's processing. Here you can use webscoket for communication.

**Comment by amkyp** [comment]
I don't know the exact seconds to put in the command.
Is there any way you could do it? (like setting the default time by using command without seconds parameter)

I calculate the entire time in seconds but after waiting an hour it was like, loading screen for 1 hour :(

**Comment by jibon57** [comment]
solved here: https://github.com/jibon57/bbb-recorder/pull/29
