### ISSUE TITLE
Can't use live recording (liveJoin.js) if the room created via Greenlight.

### ISSUE THREAD

**Issue by samuelpetrosyan** [jibon57/bbb-recorder#20]
I can't use joining via this link, where uses meetingId parameter. I have ID provided by Greenlight, such as "abc-12d-3ef". 
So it's impossible to use this link in my case.
`node liveJoin.js "https://BBB_HOST/bigbluebutton/api/join?meetingId=MEETING_ID...." liveRecord.webm 0 true`
Please instruct me a little.
Can I do something another here?

**Comment by jibon57** [comment]
Hi,

For using this module you'll have to get joining link somehow. You can try this repo: https://github.com/mconf/bigbluebutton-api-js to get link. 

Thanks

**Comment by jibon57** [comment]
try: https://github.com/jibon57/bbb-recorder/commit/7959d2bb95eb12a9c4bad62e3443dbec7149319c
