### ISSUE TITLE
Windows / MAC-OS version

### ISSUE THREAD

**Issue by zakcali** [jibon57/bbb-recorder#23]
what will happen to lines with xvfb on a MAC-OS or Windows system?
Does this code, especially export.js works with minimal modification?

**Comment by jibon57** [comment]
Hi,
If you check code here: 
https://github.com/jibon57/bbb-recorder/blob/bf6eeb2996aa0ad7d1d6a922fe2bb082cd265848/export.js#L43
You'll see `xvfb` will enable only for Linux. Because Windows & MacOS have GUI. So, I don't think you'll get any error message if you run. This line:
https://github.com/jibon57/bbb-recorder/blob/bf6eeb2996aa0ad7d1d6a922fe2bb082cd265848/export.js#L34
I have added path for Linux (ubuntu) & MacOS. I don't have any Windows device so don't know the location of Google Chrome. So, you can modify it like this:

```
if(platform == "linux"){
    options.executablePath = "/usr/bin/google-chrome"
}else if(platform == "darwin"){
    options.executablePath = "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
}else if(platform == "win32"){
	options.executablePath = " " // here you can give full path of chrome.exe
}
```
Now it should work from any platform.

**Comment by jibon57** [comment]
OK, in windows 64bit probably location of Google Chrome here:

`C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`

You can verify. So, modification will be: 
```
if(platform == "linux"){
    options.executablePath = "/usr/bin/google-chrome"
}else if(platform == "darwin"){
    options.executablePath = "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
}else if(platform == "win32"){
    options.executablePath = "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" // here you can give full path of chrome.exe
}
```

**Comment by zakcali** [comment]
I've added the path as you said but with doble backslashes, made some changes related with paths:
else if(platform == "win32"){
    options.executablePath = "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe" // here you can give full path of chrome.exe	
}

**Comment by zakcali** [comment]
I've started to download a recording, I saw a chrome tab with presentation on my desktop (I was expecting not see that tab, it is okay), but when recording ends, I got error:
ERROR: The process "18412" not found.

**Comment by zakcali** [comment]
Here are the changes I've made, and response I got, pasted all of them:
-------- run the commands below-----------
git clone https://github.com/jibon57/bbb-recorder
cd bbb-recorder
npm install --ignore-scripts
---------------------got the response-----------------------------
C:\Users\zafer\node\bbb-recorder>npm install --ignore-scripts
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN bbbrecorder@0.0.1 No repository field.
npm WARN bbbrecorder@0.0.1 No license field.
added 48 packages from 35 contributors and audited 48 packages in 3.913s
1 package is looking for funding
  run `npm fund` for details
found 0 vulnerabilities
------------------------------config.json-----------------
{
	"rtmpUrl": "rtmp://a.rtmp.youtube.com/live2/MyKey",
	"ffmpegServer": "ws://localhost",
	"ffmpegServerPort": 4000,
	"auth": "mZFZN4yc"
}
-------------------------exportjs-----------------------
deleted lines:
"copyToPath": "/var/www/bigbluebutton-default/record"
const Xvfb      = require('xvfb');
-------------------------added path to exportjs----------------------
if(platform == "linux"){
    options.executablePath = "/usr/bin/google-chrome"
}else if(platform == "darwin"){
    options.executablePath = "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
}else if(platform == "win32"){
    options.executablePath = "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe" // here you can give full path of chrome.exe	
}
------------- changed lines of exportjs -------------
    var copyFromPath = "./downloads";
    var copyToPath = "./records";
--------------------------------------------------------------
------------ created downloads and records folders------------
------------started to download a recording------------
------ waited for the end of recording, I got the error---------------------------------------------------------------
ERROR: The process "18412" not found.
[Error: EPERM: operation not permitted, unlink 'C:\Users\zafer\AppData\Local\Temp\puppeteer_dev_chrome_profile-EaDRfV\CrashpadMetrics-active.pma'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\Users\\zafer\\AppData\\Local\\Temp\\puppeteer_dev_chrome_profile-EaDRfV\\CrashpadMetrics-active.pma'
}

**Comment by zakcali** [comment]
I commented to skip closing process with this:
//        await browser.close()
But this time downloads folder is empty, and ffmpeg gives error
stderr: downloads/Egitim-264-3509-000.webm: No such file or directory

**Comment by jibon57** [comment]
Give full path of `downloads` directory. You are doing wrong for `copyFromPath`

**Comment by zakcali** [comment]
Ok. somehow, I managed the filenames with absolute paths, temporarily with this:
function copyOnly(filename){
    var copyFrom = "e:\\Downloads\\" + filename;
    var copyToPath = "records";
    var copyTo = copyToPath + "\\" + filename;  

Now, I got the web file with no-file
There is an Opus Audio track in the stream, but I don't hear a sounds/speakings

**Comment by jibon57** [comment]
I don't know how much you have modified the file. I think the default code should work perfectly if you just add chrome path as my example. Try to convert webm file to mp4 & see the result.

**Comment by zakcali** [comment]
I've solved my first problem: ERROR: The process "xxxxx" not found.
to close chrome windows, I need that code

```
for (const onepage of pages) {
	await onepage.close();
	}
await browser.close();
```
source: https://github.com/puppeteer/puppeteer/issues/1245

Still I hear no audio

**Comment by zakcali** [comment]
Here are my thoughts on Linux and Windows versions. Probably I will give up trying becuase, I see the browsers in Windows mode.
Pros:
1) Awesome
2) I don't see any browser window (maybe xvfb effect), even "  headless:false,"
3) I can start three recording in separate  shells with my intel E5450 quad core processor. Each processor is consumed %80 capacity. So I can download 20 presentation in a few hours.
Cons:
1) I have to start my Linux partition when booting my PC by pressing F11
2) There are hundreds of  educators (M.D.s) in our medical faculty, %95 of them doesn't know what is linux, %4 of them may Install a Linux system to their computers, %1 of them may compile the code and use that program (Probably I'm the only one, between 500+ educators)

Here are my thoughts on Windows version
Pros:
None
Cons:
1) no sound! no sound! no sound! When displaying in browser windows, when playing webm file, when playing converted mp4 file, I hear no sound. There is an audio track coded with Opus, stereo channels, sample rate 48000 Hz, bits per sample 32, just like on Linux version. Of course there is sound if I play the presentation from web.
2) I see the browser window, even it starts in full window, because "headless: false", So it is very difficult to do other things at the same time. I don't know what happens if I exit full screen mode. I don't know what will happen if I get sound. Could I start 2 or 3 recordings at the same time just like on Linux? I don't know. Absence of xvfb on windows terrible. We don't need to see presentation windows.
3) 		await page.close();
		await browser.close();
commands don't work well on Windows 10. I always got "ERROR: The process "xxxxx" not found."
So I commented as "// await browser.close();" 
I'm closing chrome tasks from Task manager manually after program finishes. 
4) Even I don't use I got error below randomly when program exiting:
[Error: EPERM: operation not permitted, unlink 'C:\Users\zafer\AppData\Local\Temp\puppeteer_dev_chrome_profile-xXxXxX\CrashpadMetrics-active.pma'] {
errno: -4048,
code: 'EPERM',
syscall: 'unlink',
path: 'C:\Users\zafer\AppData\Local\Temp\puppeteer_dev_chrome_profile-EaDRfV\CrashpadMetrics-active.pma'
}
5) I tried to use chromium from https://download-chromium.appspot.com., extracted the zip file to suitable directory with options:
options.executablePath = "./node_modules/puppeteer/.local-chromium/win64-769697/chrome-win/chrome.exe"

Chromium browser doesn't stop at the specified time (default is 10 sn). And as alwyas, and expected from chromium, there is no sound !

**Comment by jibon57** [comment]
I think your concept to use this solution isn't correct. Why are you trying to use this module from your local PC? You should use remote server to process recordings & provide processed MP4 to end users. Anyway I am closing this as it's not an issue.

**Comment by zakcali** [comment]
I found another fork of puppetcam, which removed xvfb dependency:
https://github.com/Ventricule/html2screen

**Comment by jibon57** [comment]
I think you are misunderstanding the purpose of using `xvfb`. Please read more from here: https://en.wikipedia.org/wiki/Xvfb
