### ISSUE TITLE
Long recordings cannot be recorded

### ISSUE THREAD

**Issue by levigo-systems** [jibon57/bbb-recorder#24]
Hello,

we have a bbb recording with 7239 secounds.
We are always running into the same issue:
`Error: Could not stop Xvfb.
    at Xvfb.stopSync (/root/bbb-recorder/node_modules/xvfb/index.js:129:17)
    at main (/root/bbb-recorder/export.js:95:18)
    at <anonymous>`

Maybe someone has an idea how to fix the problem?

We are running bbb-recorder on an Ubuntu 18.04 VM with no bbb installed.

All best

**Comment by jibon57** [comment]
Hi,
Try to remove this line:
https://github.com/jibon57/bbb-recorder/blob/bf6eeb2996aa0ad7d1d6a922fe2bb082cd265848/export.js#L95
Not sure why in your server can't close `Xvfb` process but that will be work around.

**Comment by jibon57** [comment]
Or I think **setTimout** can help here. Can you try like this:

```
setTimeout(function(){
	xvfb.stopSync();
}, 3000);
```
It's better to give it 3 seconds to clean up.

**Comment by levigo-systems** [comment]
Next test with 3 seconds timeout is running.
I will give you feedback as soon as possible. 

Thank you!

**Comment by levigo-systems** [comment]
A other error:
`/root/bbb-recorder/meeting.mp4
/root/Downloads/meeting.webm
/root/bbb-recorder/node_modules/xvfb/index.js:129
          throw new Error('Could not stop Xvfb.');
          ^

Error: Could not stop Xvfb.
    at Xvfb.stopSync (/root/bbb-recorder/node_modules/xvfb/index.js:129:17)
    at Timeout._onTimeout (/root/bbb-recorder/export.js:97:9)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
`

Should i try it without  xvfb.stopSync()  ?

**Comment by jibon57** [comment]
Are you running multiple process at a same time? Did the process was complete? I mean, did you get MP4 file output? Yes, you can try ` xvfb.stopSync()`

**Comment by levigo-systems** [comment]
No i am running only one process at the same time.

The process didn't complete, there was no MP4 file as output.

I will try without xvfb.stopSync().

**Comment by levigo-systems** [comment]
That worked! 
Thank you!!
