### ISSUE TITLE
Ejecute node from php Shell_exec

### ISSUE THREAD

**Issue by hernanct** [jibon57/bbb-recorder#25]
Hello, nice to meet you, I'm glad you have this solution for the recording of bbb, I have several ideas in my project, but I'm just really stuck with a problem that has been in it for hours.
I can't execute the comment from php shell_exec, my idea is to execute
$ dir = "/ var / www / symphony / bbbr / bbb-recorder";
chdir ($ dir);
$ result = shell_exec ('node export.js "https://mydomain.cl/playback/presentation/2.0/playback.html?meetingId=26fe41aafaa52ae721916d0f9d3ee6e0e86db3ba-1589397338630" meet.webm 10 true> / dev / null> dev / null ');
echo "<pre>";
echo $ result;
echo "</pre>";

But it hangs, and on the server, it is run by www-data but the chrome process stays running without doing anything.

but if i run the same code from command shell, everything works fine.
I have tried in many ways, thinking it was the permissions, but it is not.
Something happens that when running from the web, the process hangs.
I have realized that if I do an example:
logged in as root user:
sudo -u www-data node export.js "http://maidomain.com......" 10 true
also hangs.
and so with any user.
I would appreciate your help

**Comment by jibon57** [comment]
Most probably you'll require to run it as a root user. I never try like that in PHP. Try to use websocket to communicate with node instated of directly running from PHP.
