### ISSUE TITLE
NOT ISSUE: Hide/Resize presentation during recording

### ISSUE THREAD

**Issue by samuelpetrosyan** [jibon57/bbb-recorder#26]
Dear developer,
Thanks so much for this useful tool!

Was anyone able to **hide or resize presentation** during recording?!
Can we do it either with bbb-recorder configuration or with BigBlueButton configurations?!

Thanks in advance..

**Comment by jibon57** [comment]
You can try to add this line 

`await page.click('button[class=acorn-swap-button]', {waitUntil: 'domcontentloaded'});`

after this:
https://github.com/jibon57/bbb-recorder/blob/bf6eeb2996aa0ad7d1d6a922fe2bb082cd265848/export.js#L70

It should do toggle

**Comment by samuelpetrosyan** [comment]
It doesn't work for me...
I should add this line in export.js, shouldn't I?
