### ISSUE TITLE
Problem with Live RTMP broadcasting ffmpeg auto exit

### ISSUE THREAD

**Issue by lahirutm** [jibon57/bbb-recorder#27]
You can use a simple workaround for this to resolve. This is happen when no change detected on the screen. Therefor we can put small countdown/timer to make small content change on the screen, then chrome will capture screens continuously. We don't need to camera open then.

```
await page.evaluate(() => {	
    var btn = document.createElement("div");
    btn.innerHTML = '<div id="injected_countdown" style="text-align:left; margin-bottom:-30px; padding-bottom:-20px;">COUNTDOWN</div>';
    document.querySelector("header").appendChild(btn);
});
await page.waitFor(1000);
await page.addScriptTag({url: 'inject.js'});
```

Here is the code for java-script timer injected above.

```
function startTime() {
  var today = new Date();
  var h = today.getHours();
  var m = today.getMinutes();
  var s = today.getSeconds();
  var ms = today.getMilliseconds();
  m = checkTime(m);
  s = checkTime(s);
  document.getElementById('injected_countdown').innerHTML = h + ":" + m + ":" + s + ":" + ms;
  var t = setTimeout(startTime, 100);
}
function checkTime(i) {
  if (i < 10) {i = "0" + i};  // add zero in front of numbers < 10
  return i;
}
startTime();
```

**Comment by jibon57** [comment]
Thank you! But won't it make user confused?

**Comment by octycs** [comment]
Oh, that might also be a good idea. I faced that problem some days ago and found a "quick-fix" by making the body alternate from 1 to 0.99 opacity, which is not noticeable.

```
await page.addStyleTag({content: '@keyframes refresh {0%{ opacity: 1 } 100% { opacity: 0.99 }} body { animation: refresh .01s infinite }'})
```

However this doesn't feel like a nice solution :sweat_smile:

**Comment by jibon57** [comment]
@octycs thank you! Nice work around too!

**Comment by lahirutm** [comment]
> Thank you! But won't it make user confused?

Since it is very small and color can be set to similar background color, it is not noticeable.

**Comment by jibon57** [comment]
I am putting reference from readme to here as workaround. User can use according to their needs. Thank you all!
