### ISSUE TITLE
Specifying 0 for time duration literally make 0 size recording

### ISSUE THREAD

**Issue by bluelupin** [jibon57/bbb-recorder#28]
When I execute following command - 
node export.js "https://<mydomain>/playback/presentation/2.0/playback.html?meetingId=17c0689aa607459fc63d822848bc1475db509b8d-1586949361016" 17c0689aa607459fc63d822848bc1475db509b8d-1586949361016.webm 0 true

It doesn't consider the full recording length.

**Comment by jibon57** [comment]
Read the reademe file carefully.
