### ISSUE TITLE
FFmpeg strange behaviour

### ISSUE THREAD

**Issue by triangle-stream** [jibon57/bbb-recorder#3]
Hello there! 

First, i realli would like to thank you for this project.
I tried to use it to achieve an RTMP streaming for a conference. 
I edited the .json file in order to set the righ rtmp url and my nginx rtmp server receive the stream from bbb-recorder. 
Next, i did another thing: added a "-re" flag before "-i" on the ffmpeg arguments (this is important for ffmpeg if you want to stream live because it forces the encoding at 1x, for real time streaming).

Here is the strange:
Everytime i launch the recorder, it seems that it is capable to only create a frame recording, next ffmpeg receive the SIGINT (or similiar) command and so it stops and restart again. 
The result is that ffmpeg is able to stream only one frame of the conference in an infinite restarting loop.

I joined to meeting using the API get provided from BBB (in which i had to add fullname, password meetingID and checksum),  but it seems that bbb-recorder is able to only get a record of the first frame.

Can you help me with this?

Thank you!

**Comment by jibon57** [comment]
> Can you help me with this?
No, you missed to read that section

> Note: If you do nothing in meeting room that time ffmpeg may exit with error & will try to reconnect again. Actually I don't have much experience on ffmpeg to resolve those problems. Please contribute your experience.

**Comment by jibon57** [comment]
@triangle-stream , try to add `"-vf", "scale=1280:720",` & ` '-vcodec', 'libx264',` after `'-i', '-',`

**Comment by triangle-stream** [comment]
> Note: If you do nothing in meet

Thank you for reply. 
I added -vcodec and other flags (substitute them with -c:v and -c:a and others) and ffmpeg start streaming, so i don't think this is an ffmpeg issue.

What do you mean exactly with "If you do nothing"? How can i "do something" in the room bt using bbb-recorder?

Thank you.

**Comment by jibon57** [comment]
> What do you mean exactly with "If you do nothing"? How can i "do something" in the room bt using bbb-recorder?

The presenter should do something. Better to keep webcam on.

**Comment by triangle-stream** [comment]
I confirm that during tests the presenter was active on webcam and also a presentation was on, but nothing changed on the bbb-recorder's behaviour, unfortunately.

**Comment by jibon57** [comment]
We are using this solution almost everyday for 3~4 clients to live broadcast in YouTube. We didn't face any serious problem so far.

**Comment by triangle-stream** [comment]
Ok, thank you.
Sorry for bothering you, i'm not assuming that the recorder does not work, i'm sure it will. 

May I ask you what FFmpeg version are you running? Also, are there any other dependencies needed except ones in the Readme?

**Comment by jibon57** [comment]
I am using same version that BBB is providing. 
```
ffmpeg version 4.2.2-1bbb1~ubuntu16.04 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 20160609
```
I am using the same configuration of ffmpeg of this repo. I saw if I am using `-re` flag that time having problem on YouTube. So, you can avoid to use it. Also I am using following extra options but require more CPU:

```
'-vcodec', 'libx264',
'-x264-params', 'keyint=120:scenecut=0',
'-af', 'highpass=f=200, lowpass=f=3000',
```
but do smooth publishing on YouTube.
