### ISSUE TITLE
Real duration not working

### ISSUE THREAD

**Issue by fernandoheb** [jibon57/bbb-recorder#30]
Hello the duration parameter set as 0 is given an error. In fact it generates a webm file with 0kb so I think it is trying to generate a file with 0 sec.

node export.js "https://myhost.com/playback/presentation/2.0/playback.html?meetingId=37c684966ca3b31171552ff18c43d84697e1a763-1590149512760" 2.webm 0 true

![image](https://user-images.githubusercontent.com/10677459/83157678-450cc180-a0da-11ea-8105-5047317020d4.png)

**Comment by jibon57** [comment]
@hipoloco please have a look.

**Comment by hipoloco** [comment]
@fernandoheb are you using a custom playback.html file? Please add these lines on export.js:

![code](https://user-images.githubusercontent.com/8184347/83162230-d7639400-a0df-11ea-879f-4fd34a515cac.png)

And run the script again:

![output](https://user-images.githubusercontent.com/8184347/83162436-227da700-a0e0-11ea-812a-adfe2ec60bb5.png)

**Comment by fernandoheb** [comment]
1. Thank you very much, actually my fork wasn't up to date.
It's working just fine.
