### ISSUE TITLE
Increasing recording resolution

### ISSUE THREAD

**Issue by StormFireFox1** [jibon57/bbb-recorder#32]
Hello!

Thank you very much for this project. I would like to export 1080p recordings of the BigBlueButton recordings. I've changed the xvfb settings in `export.js` to a screen of size `1920x1200x24`, as well as the resolution of the Chrome window, but ffmpeg still reports the outputted video is 720p. Any ideas where else I have to change the resolution (if at all possible)?

Thanks in advance!

**Comment by persuader** [comment]
You must change also background.js bellow line 52 - something like this

`                        video: {
                            mandatory: {
                                chromeMediaSource: 'desktop',
                                chromeMediaSourceId: streamId,
                                minWidth: 1920,
                                maxWidth: 1920,
                                minHeight: 1080,
                                maxHeight: 1080,
                                minFrameRate: 60,
                            }
`

**Comment by StormFireFox1** [comment]
On 20/06/03 09:12PM, persuader wrote:
>You must change also background.js bellow line 52 - something like this
>
>`                        video: {
>                            mandatory: {
>                                chromeMediaSource: 'desktop',
>                                chromeMediaSourceId: streamId,
>                                minWidth: 1920,
>                                maxWidth: 1920,
>                                minHeight: 1080,
>                                maxHeight: 1080,
>                                minFrameRate: 60,
>                            }
>`

I found this before your response, but thanks so much for the help! Now
to get the bitrate up! :)

--
Matei-Alexandru Gardus (Storm_FireFox1)
https://stormhub.io
