### ISSUE TITLE
Hide Public Chat

### ISSUE THREAD

**Issue by agussang** [jibon57/bbb-recorder#36]
How to hide public chat and user list?

**Comment by jibon57** [comment]
Your question isn't clear. Which function you are using? Recording or RTMP? Because in RTMP it's already hide.

**Comment by agussang** [comment]
on RTMP
yes i look this script for hide
await page.waitForSelector('[id="chat-toggle-button"]');
        await page.click('[id="chat-toggle-button"]');
        await page.click('button[aria-label="Users and messages toggle"]');
        await page.$eval('[class^=navbar]', element => element.style.display = "none");

but it's page unhide, i looking log no error 
https://www.youtube.com/watch?v=ETnZ1nwAbRE <== this my last rtmp

any compatible?

**Comment by jibon57** [comment]
OK, make sure that your interface is in English & it isn't overriding language.

**Comment by agussang** [comment]
yes, of course in english. if failed about overrriding language, this rmtp can't start. i'm check this function
        await page.waitForSelector('[aria-label="Listen only"]');
        await page.click('[aria-label="Listen only"]', timeout);
and look like running, but on next script i think not running, can you help me? may be i can get your contact.

**Comment by jibon57** [comment]
Ok, I just did quick test from my side. It's working as expected. Just make sure that the browser language is English. If you want to support other language then you can modify code.

**Comment by agussang** [comment]
no, i'm only use english
can i get your contact for collaboration about this case

**Comment by jibon57** [comment]
You can reach me: jibon@mynaparrot.com

**Comment by agussang** [comment]
what nodejs Version? i'm using 12
can you help me check my environment. i can provide teamviewer
