### ISSUE TITLE
Is it possible for bbb-recorder to work with a Zoom URL of a meeting/webinar?

### ISSUE THREAD

**Issue by jzvi12** [jibon57/bbb-recorder#37]
My goal is to broadcast from Zoom to Facebook live using ffmpeg.

I'm thinking of running a Zoom webapp (nodejs) using the Zoom Web SDK so I can join a meeting without reCAPTCHA and somehow auto-filling out meeting details such as Meeting ID, etc... and using Puppeteer to make a few clicks like pressing "Join" and "Join Audio by Computer" buttons.

Could this be possible?

**Comment by lonesomewalker** [comment]
Use OBS, otherwise don't ask for open source solutions :P
Ask Zoom.

**Comment by jzvi12** [comment]
ধন্যবাদ

**Comment by jibon57** [comment]
আপনি আমার কোড থেকে ধারনা নিতে পারেন। তারপর নিজের মতন চেষ্টা করে দেখেন। কিন্তু আমার মনে হয়না আপনি reCAPTCHA পার করতে পারবেন। যাইহোক আমি কখনই Zoom ব্যবহার করি নাই। আর @lonesomewalker আপনাকে OBS ব্যবহার করার কথা বলেছেন। আপনি ওটা ব্যবহার করতে পারেন। ধন্যবাদ
