### ISSUE TITLE
bbb-recorder install errors

### ISSUE THREAD

**Issue by koenr** [jibon57/bbb-recorder#4]
Hi, 
Thank you for this scrip.
I tried testing it, but got stuck in installation. Could be completely due to my ignorance.

koenr@koenr-Latitude-5580:~/bbb-recorder$ npm install
loadDep:ws → resolveWithN ▐ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine puppeteer@2.1.1: wanted: {"node":">=8.16.0"} (current: {"node":"8.10
> sleep@6.1.0 install /home/koenr/bbb-recorder/node_modules/sleep
> node-gyp rebuild

make: Map '/home/koenr/bbb-recorder/node_modules/sleep/build' wordt binnengegaan
  CXX(target) Release/obj.target/node_sleep/module_init.o
  CXX(target) Release/obj.target/node_sleep/sleep_cpp11.o
  CXX(target) Release/obj.target/node_sleep/sleep_posix.o
  CXX(target) Release/obj.target/node_sleep/sleep_win.o
  SOLINK_MODULE(target) Release/obj.target/node_sleep.node
  COPY Release/node_sleep.node
make: Map '/home/koenr/bbb-recorder/node_modules/sleep/build' wordt verlaten

> puppeteer@2.1.1 install /home/koenr/bbb-recorder/node_modules/puppeteer
> node install.js

bbbrecorder@0.0.1 /home/koenr/bbb-recorder
├── UNMET PEER DEPENDENCY bufferutil@^4.0.1
├─┬ puppeteer@2.1.1 
│ ├── @types/mime-types@2.1.0 
│ ├─┬ debug@4.1.1 
│ │ └── ms@2.1.2 
│ ├─┬ extract-zip@1.7.0 
│ │ ├─┬ concat-stream@1.6.2 
│ │ │ ├── buffer-from@1.1.1 
│ │ │ ├── inherits@2.0.4 
│ │ │ ├─┬ readable-stream@2.3.7 
│ │ │ │ ├── core-util-is@1.0.2 
│ │ │ │ ├── isarray@1.0.0 
│ │ │ │ ├── process-nextick-args@2.0.1 
│ │ │ │ ├── safe-buffer@5.1.2 
│ │ │ │ ├── string_decoder@1.1.1 
│ │ │ │ └── util-deprecate@1.0.2 
│ │ │ └── typedarray@0.0.6 
│ │ ├─┬ debug@2.6.9 
│ │ │ └── ms@2.0.0 
│ │ ├─┬ mkdirp@0.5.5 
│ │ │ └── minimist@1.2.5 
│ │ └─┬ yauzl@2.10.0 
│ │   ├── buffer-crc32@0.2.13 
│ │   └─┬ fd-slicer@1.1.0 
│ │     └── pend@1.2.0 
│ ├─┬ https-proxy-agent@4.0.0 
│ │ └── agent-base@5.1.1 
│ ├── mime@2.4.4 
│ ├─┬ mime-types@2.1.26 
│ │ └── mime-db@1.43.0 
│ ├── progress@2.0.3 
│ ├── proxy-from-env@1.1.0 
│ ├─┬ rimraf@2.7.1 
│ │ └─┬ glob@7.1.6 
│ │   ├── fs.realpath@1.0.0 
│ │   ├─┬ inflight@1.0.6 
│ │   │ └── wrappy@1.0.2 
│ │   ├─┬ minimatch@3.0.4 
│ │   │ └─┬ brace-expansion@1.1.11 
│ │   │   ├── balanced-match@1.0.0 
│ │   │   └── concat-map@0.0.1 
│ │   ├── once@1.4.0 
│ │   └── path-is-absolute@1.0.1 
│ └─┬ ws@6.2.1 
│   └── async-limiter@1.0.1 
├── UNMET PEER DEPENDENCY utf-8-validate@^5.0.2
├── ws@7.2.3 
└─┬ xvfb@0.3.0 
  └─┬ sleep@6.1.0 
    └── nan@2.14.0 

npm WARN ws@7.2.3 requires a peer of bufferutil@^4.0.1 but none was installed.
npm WARN ws@7.2.3 requires a peer of utf-8-validate@^5.0.2 but none was installed.
npm WARN bbbrecorder@0.0.1 No repository field.
npm WARN bbbrecorder@0.0.1 No license field.

When running it, I get the following error message:
Error: Could not start Xvfb.
    at Xvfb.startSync (/home/koenr/bbb-recorder/node_modules/xvfb/index.js:84:17)
    at main (/home/koenr/bbb-recorder/export.js:41:18)
    at Object.<anonymous> (/home/koenr/bbb-recorder/export.js:106:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)

Running it on Ubuntu 18.04

**Comment by jibon57** [comment]
You haven't read dependencies part carefully: https://github.com/jibon57/bbb-recorder#dependencies

**Comment by jibon57** [comment]
Also if you want to convert to mp4 then you'll require `ffmpeg` library too. Tuto from here: https://linux4one.com/how-to-install-ffmpeg-on-ubuntu-18-04/

**Comment by koenr** [comment]
I'm terribly sorry. Can't believe I missed that :-(.
Thank you for pointing that out.
