### ISSUE TITLE
Convert fail if meeting is longer than 3 hours

### ISSUE THREAD

**Issue by RomainNakedCat** [jibon57/bbb-recorder#41]
Hello,

I use your code to convert presentation to mp4 it worked very well until we tried to convert long meeting (3hours+). It seems it's a limitation from exec command.

I migrate  exec command to spawnSync and now it's work fine.

Best regards,
Romain

**Comment by jibon57** [comment]
We have removed ` exec` long ago. Try the latest version & it should work perfectly.
