### ISSUE TITLE
Export.js is exporting just 1 seconds

### ISSUE THREAD

**Issue by ryprfpryr** [jibon57/bbb-recorder#47]
All the exported videos are no longer tan 0.25 seconds. I have tried different times from scratch, always same output.

Even setting name.webm 0 true or name.webm 10 true... no change

**Comment by jibon57** [comment]
There was something wrong with your system. Without more info not possible to give suggestion.

**Comment by barankaynak** [comment]
This happens when running in Docker environment on a server. However, when run with docker on desktop computer, it works fine. I am using Ubuntu 16.04 on the server.
