### ISSUE TITLE
How to run in docker.

### ISSUE THREAD

**Issue by santu-git** [jibon57/bbb-recorder#48]
Please update the document to guide how to run in docker.

**Comment by jibon57** [comment]
Hi,

I didn't write that script. It was contributed by @millad90s . Check with him if he have time to help.

**Comment by millad90s** [comment]
Hi @santu-git @jibon57 
I changed Dockefile and added few lines in README file .
clone , build image and run the container with your own arguments.

**Comment by tparesque** [comment]
Hi @millad90s , I'm having some difficulties with the docker commands, could you help me?

I executed:

`docker container run d11753ee81a5 export.js "https://ead12.proj.ufsm.br/playback/presentation/2.0/playback.html?meetingId=7e6a8534ee371f43cd24907f11bce6d364f7a700-1584959959511" meeting.webm 10 true
`

and I got the following result:

`Error: ENOENT: no such file or directory, mkdir '/var/www/bigbluebutton-default/record'
    at Object.mkdirSync (fs.js:947:3)
    at convertAndCopy (/root/bbb-recorder/export.js:169:12)
    at main (/root/bbb-recorder/export.js:147:13) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/var/www/bigbluebutton-default/record'
}`

I read the readme file, but I didn't understand the correct way to run the docker. Can you help me?
