### ISSUE TITLE
Persian chat render issue

### ISSUE THREAD

**Issue by sparse91** [jibon57/bbb-recorder#5]
Hi
Thank you for good work.
Persian characters in chat area does not render properly.

![Screenshot_20200407_141754](https://user-images.githubusercontent.com/26763315/78656071-18a7a680-78dc-11ea-8159-5a99e66c34ef.png)

**Comment by jibon57** [comment]
Are you sure the recording can be view in google chrome? I mean text are showing correctly in Google Chrome? If so then nothing wrong with this module because it just doing screen video recording.

**Comment by sparse91** [comment]
Yes.
Can this issue be font related?

**Comment by jibon57** [comment]
> Yes.

Can you see text from Google Chrome? Or having problem to view from Google Chrome too?

**Comment by sparse91** [comment]
Text are showing correctly in Chrome and Firefox.

**Comment by jibon57** [comment]
hmm mm... then may be bug with Google Chrome of Linux. Sorry, don't know how to solve

**Comment by sparse91** [comment]
I'm converting on an Ubuntu 18.04 server with no GUI. Is this matter?

**Comment by sparse91** [comment]
> Text are showing correctly in Chrome and Firefox:
> 
> ![Screenshot_20200407_144754](https://user-images.githubusercontent.com/26763315/78657988-d6339900-78de-11ea-835d-ac9a648640e6.png)

This is Google Chrome on Linux Desktop.

**Comment by jibon57** [comment]
You can follow https://support.google.com/chrome/thread/5705492?hl=en or search for similar

**Comment by sparse91** [comment]
Ok. I will try them. Thank you.

**Comment by sparse91** [comment]
It was font. Installing `noto-fonts` solved the problem.
