### ISSUE TITLE
Sometimes exported video contains only black screen or 1-2 seconds of the full video

### ISSUE THREAD

**Issue by miriyusifli** [jibon57/bbb-recorder#50]
First of all, Thanks for sharing the code with others.

I have tested the **export.js**. It works as expected but I faced some situations in which the exported video contained a black screen or only 1-2 sec of the full video whose length was 2-3 mins. Only after re-running the script, I got the expected result.

Do you have an idea of how can this problem be solved?

Thanks in advance.

**Comment by jibon57** [comment]
It's expected. It will start recording as soon as few params will fulfill. Your problem mostly happening for connectivity problem.
