### ISSUE TITLE
Livejoin: Audio is lost if meeting is disconected

### ISSUE THREAD

**Issue by ryprfpryr** [jibon57/bbb-recorder#51]
If the meeting disconects for some seconds and reconnects, the recorder looses the audio and does not reconnect as a listener. This happened in a 3 hour session on which at 1:30 the server disconected for some seconds, and the last half of the meeting there is only video without sound.

**Comment by jibon57** [comment]
This is expected. You are sending a bot user. It can't understand what's happening there. It'll just record screen & initially click to join as listen only mood. It don't know in which situation what need to do. You can read this section: https://github.com/jibon57/bbb-recorder#how-it-will-work
