### ISSUE TITLE
bbb-recorder (ffmpeg) runs out of memory when streaming live to RTMP

### ISSUE THREAD

**Issue by glunardi** [jibon57/bbb-recorder#55]
This is not directly related to bbb-recorder but hoping you could assist us.

We have been testing with bbb-recorder to rtmp live stream BBB sessions to YouTube Live. Thank you for your work, the project is well put together.

Our issue:
`ffmpeg` runs out of memory after some time depending on the size of the host (VMs). We are using Linode as our provider.

Looks like with:
-  2 VCPU / 4 GB it fails after less than 5 minutes
-  4 VCPU / 8 GB it fails after about 38 minutes

```
[ 4521.946279] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=6fe9a17c458df671ac76e9d83081eab78508fd7c9063ad98c9c4fd4085c653fb,mems_allowed=0,global_oom,task_memcg=/docker/6fe9a17c458df671ac76e9d83081eab78508fd7c9063ad98c9c4fd4085c653fb,task=ffmpeg,pid=3529,uid=0
[ 4521.946350] Out of memory: Killed process 3529 (ffmpeg) total-vm:8860260kB, anon-rss:7688164kB, file-rss:0kB, shmem-rss:12812kB, UID:0 pgtables:16288kB oom_score_adj:0
[ 4522.378152] oom_reaper: reaped process 3529 (ffmpeg), now anon-rss:16kB, file-rss:0kB, shmem-rss:12832kB
[ 4523.638944] br-42362ca21fc0: port 1(vetha0a8f11) entered disabled state
[ 4523.639298] veth4950752: renamed from eth0
[ 4523.714325] br-42362ca21fc0: port 1(vetha0a8f11) entered disabled state
[ 4523.718378] device vetha0a8f11 left promiscuous mode
[ 4523.718387] br-42362ca21fc0: port 1(vetha0a8f11) entered disabled state

```

Seems it might be related to the audio capture. We are using your pulseaudio daemon settings and all ffmpeg settings.

What we are hoping for:
- We would like to be able to stream live (RTMP to YouTube Live) one session for up to 5 hours.

Our questions
- Is that an issue you have ran into perhaps?
- What size systems (CPU/RAM) are you using to run the bbb-recorder for live RTMP streaming for that sort of duration?

**Comment by jibon57** [comment]
2 VCPU / 4 GB it fails after less than 5 minutes
> Are you sure that you are getting dedicated CPU? For my project I am running similar & can easily run 2 sessions at a same time for more than 2 hours. I don't think you're getting full CPU power.

**Comment by glunardi** [comment]
> > 2 VCPU / 4 GB it fails after less than 5 minutes
> 
> Are you sure that you are getting dedicated CPU? For my project I am running similar & can easily run 2 sessions at a same time for more than 2 hours. I don't think you're getting full CPU power.

Thank you for your reply and you are correct. I was attempting to run on shared vcpu VMs. 

Gave up and spun up a dedicated CPU for a few tests and things are much better there. There are still some occasional frame sync issues between xvfb and ffmpeg but that is almost normal I suppose.

Streamed for 6 hours+ a few times now. 

Thank you very much for your project and your answer.
