### ISSUE TITLE
.env file support

### ISSUE THREAD

**Issue by amirhoseinsalimi** [jibon57/bbb-recorder#56]
Hello,

IMHO .env file is a nice thing to have for such a project. It provides:
- Painless clustering for isolated environments e.g. Docker
- In-place support on cloud platforms
- More naturalness for other developers

Caveat? The `config.json` file would be deleted and modules requiring env. variables should import the variables, but we can export the whole env. variable as a single object to maximize the code re-use.

What does this need?
- Delete `config.json` file
- Setup .env variables (with a small `.env.example`)
- Update `README.md`

I can work on this and send a PR if you're interested in the issue.

**Comment by lonesomewalker** [comment]
? not wanted?

**Comment by jibon57** [comment]
Sorry, I reopened it. Pull request is welcome. Later can see how it goes.
