### ISSUE TITLE
getting "Session closed. Most likely the page has been closed." in many bbb-meetings

### ISSUE THREAD

**Issue by sachin440** [jibon57/bbb-recorder#58]
i am getting following error for some bbb-meetings bbb has meeting url
id: '900',
0|Recorder-APP  |   status: false,
0|Recorder-APP  |   state: 'Server Error, Something went wrong.',
0|Recorder-APP  |   url: null,
0|Recorder-APP  |   bucket_url: null,
0|Recorder-APP  |   error: Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
0|Recorder-APP  |       at CDPSession.send (/home/ubuntu/bbb-recording/node_modules/puppeteer/lib/Connection.js:180:29)
0|Recorder-APP  |       at ExecutionContext._evaluateInternal (/home/ubuntu/bbb-recording/node_modules/puppeteer/lib/ExecutionContext.js:107:44)
0|Recorder-APP  |       at ExecutionContext.evaluate (/home/ubuntu/bbb-recording/node_modules/puppeteer/lib/ExecutionContext.js:48:23)
0|Recorder-APP  |       at ExecutionContext.<anonymous> (/home/ubuntu/bbb-recording/node_modules/puppeteer/lib/helper.js:112:23)
0|Recorder-APP  |       at DOMWorld.evaluate (/home/ubuntu/bbb-recording/node_modules/puppeteer/lib/DOMWorld.js:112:20)
0|Recorder-APP  |     -- ASYNC --
0|Recorder-APP  |       at Frame.<anonymous> (/home/ubuntu/bbb-recording/node_modules/puppeteer/lib/helper.js:111:15)
0|Recorder-APP  |       at Page.evaluate (/home/ubuntu/bbb-recording/node_modules/puppeteer/lib/Page.js:860:43)
0|Recorder-APP  |       at Page.<anonymous> (/home/ubuntu/bbb-recording/node_modules/puppeteer/lib/helper.js:112:23)
0|Recorder-APP  |       at recordVideo (/home/ubuntu/bbb-recording/routes/index.js:212:16)

**Comment by jibon57** [comment]
I think this is happening because of `xvfb` wasn't install or running.
