### ISSUE TITLE
Recording URL unreachable!

### ISSUE THREAD

**Issue by CamZie** [jibon57/bbb-recorder#68]
Hello,

We have installed the script as documented and tried to run it for our recordings but we are receiving the following error. We can access the URL manually so it should be correct.

```
~/bbb-recorder$ node export.js "https://<REMOVED>/playback/presentation/2.0/playback.html?meetingId=<REMOVED>" presentation.mp4 0 true

Recording URL unreachable!
```

We are using debian 10 with nodejs version v14.11.0

**Comment by jibon57** [comment]
`(Optional) Export file name (should be .webm at end). You can use "MEETING_ID" (without .webm) to set the meeting ID as export name. Default: MEETING_ID`

**Comment by CamZie** [comment]
@jibon57 Thanks for the tip, I have now adapted the command as you requested but still same error. The URL is valid because we can access it on the browser.

```
~/bbb-recorder$ node export.js "https://<REMOVED>/playback/presentation/2.0/playback.html?meetingId=<REMOVED>" meeting.webm 0 true
Recording URL unreachable!
```

**Comment by jibon57** [comment]
If you have a look here:
https://github.com/jibon57/bbb-recorder/blob/126e31d2103144c2473e559dfa5a61d54848733a/export.js#L56
You'll understand that link you have provided isn't valid.

**Comment by jibon57** [comment]
also you can try the validate link using CURL to make sure that your server have access to that URL

**Comment by CamZie** [comment]
Did that already and still the same...

**Comment by amirhoseinsalimi** [comment]
I used to get the same issue on my local/development machine, but on a production server everything was fine, and I blamed the internet connection. So make sure your proxy is configured properly on the machine facing the error. A good way to see what is happening inside the browser instance is to make screenshots using Puppeteer API at different stages and verify that everything is working ok. It's like:
```
await page.screenshot({ path: 'screenshot.png '});
```

Another way to debug is to change the line:
https://github.com/jibon57/bbb-recorder/blob/126e31d2103144c2473e559dfa5a61d54848733a/export.js#L96

to this (Be aware of `networkidle0`):
```
await page.goto(url, { waitUntil: 'networkidle0', timeout: 60000 }).catch(e => {
  console.error('Recording URL unreachable!');
  console.log(e);
  process.exit(2);
})
```

**Comment by CamZie** [comment]
Hello, it looks like we had some problems with the proxy on google chrome regarding the SSL certificate.

As a workaround, we have added the chrome parameter in the export.js file on line 31 after that it worked:
`    '--ignore-certificate-errors',`
