### ISSUE TITLE
 decoding for stream 1 failed

### ISSUE THREAD

**Issue by millad90s** [jibon57/bbb-recorder#71]
I am running bbb-recorder on docker and some containers got  **decoding for stream 1 failed** error in in ffmpeg step.
how can i tshoot !?

![Screenshot from 2020-09-27 19-48-12](https://user-images.githubusercontent.com/7265793/94370055-69b18e00-00fa-11eb-992e-e6f2d12f3120.png)

**Comment by jibon57** [comment]
@sureronald will you please have a look?

**Comment by millad90s** [comment]
> @sureronald will you please have a look?

looking to what ? :)
I think its something related to chrome or ffmpeg or xvfb !?

**Comment by sureronald** [comment]
I am not an expert in ffmpeg but since you say 'some containers' maybe you want to pay more attention to the input data/sources. Are you exporting recordings or doing live broadcast?

**Comment by millad90s** [comment]
Hi 
I am exporting records with convert variable as true.
