### ISSUE TITLE
Chrome not closing after meeting ended

### ISSUE THREAD

**Issue by magnaapps** [jibon57/bbb-recorder#73]
Upgraded to 2.2.28, now the ffmpeg and chrome keeps running at the background. On the stream it keeps showing Meeting has ended but not cutting the stream. It was working well with 2.2.22 BBB version

**Comment by jibon57** [comment]
Hi,

Can you try to replace this line:
https://github.com/jibon57/bbb-recorder/blob/c94e0348829e12269621e189e26be80f1bef538e/liveRTMP.js#L96

```
await page.waitForSelector('[class^=modal] > [class^=content] > button[description="Logs you out of the meeting"]', {
                timeout: 0
            });
```
with

```
await page.waitForSelector('button[description="Logs you out of the meeting"]', {
                timeout: 0,
                visible: true
            })
            .then(() => console.log('Found selector closing!! '));
```

& update me if that solve the problem?

**Comment by magnaapps** [comment]
After the update as above, the streamer user now kicked out of the conference room after a minute and close the stream

**Comment by withitren** [comment]
yes ,It works!
