### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by OpneMind** [jibon57/bbb-recorder#74]
hi
How to disable chrom gpu?

`
/opt/google/chrome/chrome --type=zygote --no-zygote-sandbox --no-sandbox --user-data-dir=/tmp/puppeteer_dev_chrome_profile-eZdukP
/opt/google/chrome/chrome **--type=gpu-process** --field-trial-handle=870053732109817632,5942852232310198400,131072 --enable-features=NetworkService,NetworkServiceInProcess --disable-features=TranslateUI --no-sandbox --disable-dev-shm-usage --disable-breakpad --user-data-dir=/tmp/puppeteer_dev_chrome_profile-eZdukP **--gpu**-preferences=MAAAAAAAAAAgAAAQAAAAAAAAAAAAAAAAAABgAAAAAAAQAAAAAAAAAAAAAAAAAAAACAAAAAAAAAA= --shared-files

`

thanks a lot

**Comment by jibon57** [comment]
Please ask this question here: https://github.com/puppeteer
