### ISSUE TITLE
Difficulties with long recordings

### ISSUE THREAD

**Issue by henriquebol** [jibon57/bbb-recorder#8]
With small files / times it is working very well.

Sometimes the last few minutes of the video seem corrupted, but it doesn't get in the way. It seems to record, approximately, 3 minutes more than we put in the parameter. It happens with long or short recordings.

I tested with a recording of + 2h, but some problems happen:

- The error maxBuffer exceeded happens. I increased the maxBuffer in the exec. The error no longer happens, but the final file appears corrupted, it does not open on all players. In VLC it seems kind of crashing, but it could be my pc or codec, I converted it on youtube and it looks ok. Is it possible to exchange exec for spawn?

- Sometimes, when there is a longer delay in the initial loading of the page, apparently the play button is not activated and only records a black screen.

Congratulations and thanks for sharing.

**Comment by jibon57** [comment]
I think the performance will be based on your server. We are using separate server for this purpose. This project is just an example so you can do your own development. We are happy with this so far.
