### ISSUE TITLE
Unreachable URL Error

### ISSUE THREAD

**Issue by azamrashid** [jibon57/bbb-recorder#86]
I used Command after installing all dependencies and packages
node export.js "https://webconf.math.cnrs.fr/playback/presentation/2.0/playback.html?meetingId=75a2b065370729d36ebf62af77cfed12188c469e-1611057450210" meeting.webm 10 true

Found Error: Recording URL Unreachable

URL Perfectly open in Web Browser and 
BBB_HOST = webconf.math.cnrs.fr/

Kindly provide the solution for downloading such above URL Recording.

**Comment by jibon57** [comment]
Make sure your system is able to access url.
