### ISSUE TITLE
corrupted recording with Chrome 88+

### ISSUE THREAD

**Issue by sparse91** [jibon57/bbb-recorder#89]
It seems using Chrome 88 and newer sometimes leads to corrupted mp4. Slides won't record and only there is a BBB Icon in the center of the page.
I got same results this with Chrome 88 and 90. Chrome 87 is just fine. I'm using Ubuntu 18.04.

**Comment by jibon57** [comment]
You may try https://browser.taokaizen.com/ v74.0.3860.0
