### ISSUE TITLE
PAGE LOG: Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by dimitrisal** [jibon57/bbb-recorder#9]
Hello i am trying to convert a video that is a bit over 67 minutes long but i get this error when i put 4030 seconds

PAGE LOG: Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH

If i put something like 20 seconds , it works.

Any ideas? Thanks

**Comment by jibon57** [comment]
You can avoid this. It's console log output. You can remove this line if you don't want to see log:

https://github.com/jibon57/bbb-recorder/blob/5a277af641a996898439ad4927041d21d78165fe/export.js#L60
