### ISSUE TITLE
Tring to  Recording on sperate server  

### ISSUE THREAD

**Issue by shahidge4** [jibon57/bbb-recorder#90]
Dear Hi,
  i am trying to record live meeting on separate server .  the process running even the meeting is ended. and not found any recorded file on save path.

**Comment by jibon57** [comment]
You can try to change here:
https://github.com/jibon57/bbb-recorder/blob/f2520ca2bbdc0714ee63fe1cd30edc41ef25a625/liveJoin.js#L93
Like this:
https://github.com/jibon57/bbb-recorder/blob/f2520ca2bbdc0714ee63fe1cd30edc41ef25a625/liveRTMP.js#L96
